# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autocomplete < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/autocomplete/releases/download/v0.5.0/autocomplete-darwin-x86_64"
      sha256 "cf1fa0bc0b1f4d574f15b32df52aab247a710e5606fc02ad8416e925df62aea9"

      def install
        bin.install "autocomplete"
        bash_output = Utils.safe_popen_read(bin/"autocomplete", "completion", "bash")
        (bash_completion/"autocomplete").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"_autocomplete", "completion", "zsh")
        (zsh_completion/"_autocomplete").write zsh_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/J-Thompson12/autocomplete/releases/download/v0.5.0/autocomplete-darwin-arm64"
      sha256 "c1b9a98b3e1eed0e094e5dc4ab200acedeef0f6f646e32a3724a771574078475"

      def install
        bin.install "autocomplete"
        bash_output = Utils.safe_popen_read(bin/"autocomplete", "completion", "bash")
        (bash_completion/"autocomplete").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"_autocomplete", "completion", "zsh")
        (zsh_completion/"_autocomplete").write zsh_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/autocomplete/releases/download/v0.5.0/autocomplete-linux-x86_64"
      sha256 "b42d23ac3cd7f21cba2fd10ca18ab7a7379d0384dd8e8f29ba95ea2276e60641"

      def install
        bin.install "autocomplete"
        bash_output = Utils.safe_popen_read(bin/"autocomplete", "completion", "bash")
        (bash_completion/"autocomplete").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"_autocomplete", "completion", "zsh")
        (zsh_completion/"_autocomplete").write zsh_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-Thompson12/autocomplete/releases/download/v0.5.0/autocomplete-linux-arm64"
      sha256 "30bf37630b33f37d1f0a593b1aefb18e44a5a85241fa43c6d801c86d57eaafbd"

      def install
        bin.install "autocomplete"
        bash_output = Utils.safe_popen_read(bin/"autocomplete", "completion", "bash")
        (bash_completion/"autocomplete").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"_autocomplete", "completion", "zsh")
        (zsh_completion/"_autocomplete").write zsh_output
      end
    end
  end

  test do
    system "#{bin}/autocomplete"
  end
end
