# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitopsTest < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.3.8-rc0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc0/gitops-darwin-x86_64"
      sha256 "202309b96ffbb14b5664293199a4ca1be75cc0b4dffeebf554f6bf4bda7e1892"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc0/gitops-darwin-arm64"
      sha256 "804c7b874ac30ef1871814cb7c9d15c73369321c0edcf6ebc7b1b8b0bc7e3565"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc0/gitops-linux-arm64"
      sha256 "6fd3db8bc3001c706620cd47c0c5d9c70e2d9048964965608a114495422fd44f"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc0/gitops-linux-x86_64"
      sha256 "de76bf684a7691eb249518764c309f020ead5f72bbf44b8c3afc88947fb9ceb0"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
  end

  test do
    system "#{bin}/gitops-test --version"
  end
end
