# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitops < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.3.8-rc28"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc28/gitops-darwin-x86_64.tar.gz"
      sha256 "af3b1c942a7aa304d9b9762faf753ca90e31a27cafe6e44a6047a1501f7e3faa"

      def install
        bin.install "gitops"

        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc28/gitops-darwin-arm64.tar.gz"
      sha256 "b92da227fb31bcd23b3bffe499ce6c11a9ae7bd0cb756f47d2a6bc81995c881f"

      def install
        bin.install "gitops"

        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc28/gitops-linux-x86_64.tar.gz"
      sha256 "db58343fc3a5b650f296181e043ef848fc0de08b31945b1477ab8fffeb747c3c"

      def install
        bin.install "gitops"

        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc28/gitops-linux-arm64.tar.gz"
      sha256 "82b9da7c4dfbd16385ebd7fea952520eb6c2680fd5ed48e18d62f1d09e6c64ed"

      def install
        bin.install "gitops"

        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output

        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
  end

  head "https://github.com/weaveworks/weave-gitops/releases/download/latest_release/gitops_Darwin_amd64.tar.gz"
end
