# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitops < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.3.8-rc6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc6/gitops-darwin-arm64"
      sha256 "beb4c93961482b83b2d49952f9b9f5d3f2f2a30236e992c7a093c19be43d3584"

      def install
        bin.install "gitops"
        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc6/gitops-darwin-x86_64"
      sha256 "4afd7a27c25e6ce2c8fd0ec6c071948c207966e4b23ab1484b031199515ea657"

      def install
        bin.install "gitops"
        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc6/gitops-linux-x86_64"
      sha256 "7e00a5ccc256ad29556401867184355f342d81d21f3599d92cd521fbc2f560dc"

      def install
        bin.install "gitops"
        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.8-rc6/gitops-linux-arm64"
      sha256 "fc78398bdbcb4a13355de0aa34c5b0250ba9d04c760fdbc52bb837a7bf5d4804"

      def install
        bin.install "gitops"
        bash_output = Utils.safe_popen_read(bin/"gitops", "completion", "bash")
        (bash_completion/"gitops").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops", "completion", "zsh")
        (zsh_completion/"_gitops").write zsh_output
      end
    end
  end

  test do
    system "#{bin}/gitops version"
  end
end
