# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitopsTest < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.3.7-rc0.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.7-rc0.3.7/gitops-darwin-x86_64"
      sha256 "7e4d7b34cc9130132366f3bef99a332886555b1540e6fd458bb1f5523776019f"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.7-rc0.3.7/gitops-darwin-arm64"
      sha256 "f84888795d979a806d70c1140dec291fc130293ac58bc81c4f77dab5fd30ff23"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.7-rc0.3.7/gitops-linux-x86_64"
      sha256 "6f2f395c9a847001f11fc0b7d775fa94eb7f2a75cc42a2afd534f79760cdebc0"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/J-Thompson12/weave-gitops/releases/download/v0.3.7-rc0.3.7/gitops-linux-arm64"
      sha256 "a58358f746d80acf427c0e5d420998772862094a0066cc4268fed8803970f2a6"

      def install
        bin.install "gitops-test"
        bash_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "bash")
        (bash_completion/"gitops-test").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"gitops-test", "completion", "zsh")
        (zsh_completion/"gitops-test").write zsh_output
      end
    end
  end

  test do
    system "#{bin}/gitops-test --version"
  end
end
